spring:
  application:
    name: xiaozhounandu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.193.124.96:3306/xiaozhounandu?useSSL=false&serverTimezone=UTC
    username: root
    password: xiaozhounandu

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xiaozhounandu.entity
  configuration:
    map-underscore-to-camel-case: true

