# 本地开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaozhounandu_v2?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root

logging:
  level:
    com.xiaozhounandu: DEBUG
    org.springframework.web: DEBUG